version: "3.8"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    command:
      go run ./cmd/web/main.go -b 0.0.0.0
    # command: 
    #   go test -v ./...
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "80:8080"
    volumes:
      - ./backend/docs:/usr/share/nginx/html/doc
    environment:
      API_URL: backend/docs/openapi.yml
volumes:
  postgres-db:
  redis:
  redis-config: